### PR TITLE
added per host bypass (whitelist) option

### PR DESCRIPTION
**Pull request by kgbvax**
Running the Confluence&JIRA on-prem with DUO and the current plugin breaks Confluence<->JIRA integration since API calls between the two systems fail. This change permits individual hosts to be excluded from 2FA (whitelisting).
In practice one would whitelist the JIRA host(s) and potentially also 127.0.0.1.

This also resolves 50% of support case ***.

(It is also believed to cause additional issues for plugins that perform a REST call to the current Confluence/JIRA instance, like for example Scroll Office exporters)

Howto:
Add an init-param the duo- in /confluence/WEB-INF/web.xml "duoauth" filter like this:

    <param-name>bypass.hosts</param-name>
            <param-value>10.1.1.2 10.1.1.3 127.0.0.1</param-value>
      </init-param>

Hosts have to be numeric (no symbolic names) and are seperated by a " ". IPv6 should work but is untested. If you want to see what's going on, configure "com.duosecurity.seraph.filter" with log level "DEBUG" in the Confluence admin "Logging & Profiling section".

I will preparere a similar change for the JIRA plugin.
Tested on Confluence 6.10.0.
Works with reverse proxies via Tomcat's RemoteIpValve (which need to be configured in server.xml)

### CODE REVIEW

**Comment by DuoKristina** [comment]
Thanks for the PR!

We're tracking this internally nw, but I can't give you a timeline as to if/when we'd pull it in. I'll make sure to keep you posted on here when we know more.

Feel free to fork this repo to use your fix.

**Comment by Sharkking** [comment]
Is there any Update on this ?

**Comment by AaronAtDuo** [comment]
@Sharkking @kgbvax Thanks for your interest in addressing the issues with the Confluence <-> JIRA interaction and the Duo plugin.  This has been an concern for us at Duo as well.  We know that the usability of the plugin is significantly hampered by these problems, but we are very reluctant to address this problem by expanding our whitelisting functionality.  Every hole we purposely make in the plugin creates that much more of a vulnerability.  On the other hand, we know that the realistic alternative is probably for people to disable the plugin entirely; and some security is better than none.

We would be very interested in getting your input on this.  For instance, how do you currently address or work around these types of issues?

We would especially be interested in any ideas you may have on other ways to resolve this problem, that don't require additional whitelisting functionality.

**Comment by kgbvax** [comment]
>We would be very interested in getting your input on this. For instance, how do you currently address or work around these types of issues?

The attached pull request is the workaround.  

>We know that the usability of the plugin is significantly hampered by these problems
Usability of the plugin? I am under the impression that you are unaware of extend of breakage.
This breaks the Confluence<->JIRA integration which is a highly relevant feature.
For example any self-help in JIRA Service Desk is totally broken.

**Comment by OAK-UNI** [comment]
I really need that host white list too, I don't see a problem with adding as an option... I agree with everything kgbvax is saying.

**Comment by AaronAtDuo** [comment]
Thank you for your interest in Duo and for submitting this PR.  However, Duo has decided to deprecate this repository and we will not be acting on any issues or PRs on this repository going forward.  We encourage our customers to migrate their applications to the new Universal Prompt, to take advantage of improved security, user experience, and customization features.  You can find more information on migrating to the Universal Prompt at https://duo.com/docs/universal-prompt-update-guide.

You can also find more information about the deprecation at https://duosecurity.github.io/faq.html.

Thanks again for using Duo!

**Pull request closed without merging**
